// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'Octogone';

  @override
  String get retry => 'Retry';

  @override
  String get loading => 'Loading…';

  @override
  String errorWithMessage(String message) {
    return 'Error: $message';
  }

  @override
  String toVerify(String fields) {
    return 'To verify: $fields';
  }

  @override
  String get missingConfig =>
      'Supabase configuration missing.\n\nBuild with:\nflutter run --dart-define-from-file=config/app.json\n\n(file generated by scripts/supabase_setup.sh)';

  @override
  String get authTagline => 'Fighter cards among friends';

  @override
  String get email => 'Email';

  @override
  String get password => 'Password';

  @override
  String get signIn => 'Sign in';

  @override
  String get noAccount => 'No account yet? Create one';

  @override
  String get invalidEmail => 'Invalid email';

  @override
  String get passwordRequired => 'Password required';

  @override
  String get signupTitle => 'Create an account';

  @override
  String get pseudo => 'Username';

  @override
  String get pseudoMin => 'At least 3 characters';

  @override
  String get pseudoChars => 'Letters, digits, space, “_”, “-” or “.”';

  @override
  String get passwordMinLabel => 'Password (min. 8 characters)';

  @override
  String get passwordMin => 'At least 8 characters';

  @override
  String get confirmPassword => 'Confirm password';

  @override
  String get passwordsDiffer => 'Passwords don’t match';

  @override
  String get createAccount => 'Create my account';

  @override
  String get pseudoTaken => 'This username is already taken.';

  @override
  String get errInvalidCredentials => 'Wrong email or password.';

  @override
  String get errAlreadyRegistered =>
      'An account already exists with this email.';

  @override
  String get errPasswordShort => 'Password too short (8 characters minimum).';

  @override
  String get errEmailNotConfirmed => 'Email not confirmed.';

  @override
  String get errRateLimit => 'Too many attempts: try again in a few minutes.';

  @override
  String get errNoInternet => 'No internet connection.';

  @override
  String errUnexpected(String message) {
    return 'Unexpected error: $message';
  }

  @override
  String get navHome => 'Home';

  @override
  String get navAlbum => 'Album';

  @override
  String get navFighters => 'Fighters';

  @override
  String get navFight => 'Fight';

  @override
  String get navProfile => 'Profile';

  @override
  String helloUser(String pseudo) {
    return 'Hi $pseudo!';
  }

  @override
  String get sync => 'Sync';

  @override
  String get syncRunning => 'Syncing content…';

  @override
  String get syncOffline => 'Offline: cached content';

  @override
  String syncUpToDate(String date) {
    return 'Up to date ($date)';
  }

  @override
  String syncUpToDateReceived(String date, int count) {
    return 'Up to date ($date) · $count items received';
  }

  @override
  String get syncWaiting => 'Waiting for sync';

  @override
  String get statFighters => 'fighters';

  @override
  String get statChampions => 'champions';

  @override
  String get statEditions => 'editions';

  @override
  String get statMyCards => 'cards';

  @override
  String get browseEditions => 'My album';

  @override
  String get browseEditionsSub => 'Binders by edition, completion, filters';

  @override
  String get allFighters => 'All fighters';

  @override
  String get allFightersSub => 'Real stats and game stats';

  @override
  String get dailyBooster => 'Daily booster';

  @override
  String get comingPhase3 => 'Coming in phase 3';

  @override
  String get welcomePack => 'Welcome pack';

  @override
  String get welcomePackSub => '15 free cards, including rares';

  @override
  String get welcomePackOpen => 'Open';

  @override
  String welcomePackReceived(int count) {
    return 'You received $count cards!';
  }

  @override
  String get welcomePackAlready => 'Welcome pack already received';

  @override
  String get effectsShowcase => 'Effects gallery';

  @override
  String get effectsShowcaseSub => 'Preview every rarity';

  @override
  String get fightersTitle => 'Fighters';

  @override
  String get searchFighters => 'Search a name or nickname';

  @override
  String get champions => 'Champions';

  @override
  String get downloadingFighters => 'Downloading fighters…';

  @override
  String get downloadFailed =>
      'Couldn’t download content. Check your connection.';

  @override
  String get noFighters => 'No fighters yet.';

  @override
  String get fighterNotFound => 'Fighter not found';

  @override
  String get unknownCountry => 'Unknown country';

  @override
  String get categoryToVerify => 'Division to verify';

  @override
  String recordLabel(String record) {
    return 'Record $record';
  }

  @override
  String get tagChampion => 'Champion';

  @override
  String get tagChampionF => 'Champion';

  @override
  String get tagFormerChampion => 'Former champion';

  @override
  String get tagFormerChampionF => 'Former champion';

  @override
  String get tagRetired => 'Retired';

  @override
  String get tagRetiredF => 'Retired';

  @override
  String get gameStats => 'Game stats';

  @override
  String get gameStatsNote => 'Computed from the real statistics below.';

  @override
  String get ufcStats => 'UFC statistics';

  @override
  String get sigStrikesPerMin => 'Significant strikes / min';

  @override
  String get strikeAccuracy => 'Striking accuracy';

  @override
  String get strikesAbsorbed => 'Strikes absorbed / min';

  @override
  String get strikeDefense => 'Striking defense';

  @override
  String get takedownsPer15 => 'Takedowns / 15 min';

  @override
  String get takedownAccuracy => 'Takedown accuracy';

  @override
  String get takedownDefense => 'Takedown defense';

  @override
  String get subsPer15 => 'Submission attempts / 15 min';

  @override
  String get knockdownsPer15 => 'Knockdowns / 15 min';

  @override
  String get avgFightTime => 'Average fight time';

  @override
  String minutesSeconds(int min, String sec) {
    return '$min min $sec';
  }

  @override
  String get proRecord => 'Professional record';

  @override
  String get wins => 'Wins';

  @override
  String get losses => 'Losses';

  @override
  String get draws => 'Draws';

  @override
  String get noContests => 'No contests';

  @override
  String methodBreakdown(String total, String ko, String sub, String dec) {
    return '$total  (KO $ko · Sub. $sub · Dec. $dec)';
  }

  @override
  String get ufcFights => 'UFC fights';

  @override
  String ufcFightsValue(String total, String wins, String losses) {
    return '$total ($wins W – $losses L)';
  }

  @override
  String get bonusFotn => '“Fight of the Night” bonuses';

  @override
  String get bonusPotn => '“Performance of the Night” bonuses';

  @override
  String get fiveRoundDecisions => 'Five-round decision wins';

  @override
  String get distinctions => 'Achievements';

  @override
  String cardsCount(int count) {
    return 'Cards ($count)';
  }

  @override
  String get albumTitle => 'Album';

  @override
  String get realEditions => 'Real editions';

  @override
  String get originalEditions => 'Original editions';

  @override
  String get noEditions => 'No edition cached yet.';

  @override
  String editionCards(int count) {
    return '$count cards';
  }

  @override
  String get originalCreation => 'original creation';

  @override
  String releaseDate(String date) {
    return 'Released: $date';
  }

  @override
  String seriesCount(int count) {
    return '$count series';
  }

  @override
  String get parallels => 'Parallels';

  @override
  String numberedSeries(int n) {
    return 'numbered /$n';
  }

  @override
  String oddsLabel(String odds) {
    return 'odds $odds';
  }

  @override
  String get checklistSources => 'Checklist sources';

  @override
  String get seriesBase => 'Base';

  @override
  String get seriesAutographs => 'Autographs';

  @override
  String get seriesRelics => 'Relics';

  @override
  String get seriesMoments => 'Historic Moments';

  @override
  String get seriesCelebrations => 'Celebrations';

  @override
  String get seriesInsert => 'Insert';

  @override
  String completion(int owned, int total, int pct) {
    return '$owned/$total · $pct%';
  }

  @override
  String pageOf(int page, int total) {
    return 'Page $page/$total';
  }

  @override
  String get filterAllRarities => 'All rarities';

  @override
  String get filterAllCategories => 'All divisions';

  @override
  String get filterOwnedOnly => 'Owned';

  @override
  String get filterSearchFighter => 'Fighter…';

  @override
  String get checklistView => 'Checklist';

  @override
  String get binderView => 'Binder';

  @override
  String get notOwned => 'Not owned';

  @override
  String ownedCopies(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count copies',
      one: '1 copy',
    );
    return '$_temp0';
  }

  @override
  String get emptySlot => 'Empty slot';

  @override
  String get cardFlipHint => 'Tap the card to flip it';

  @override
  String get cardTiltHint => 'Tilt your phone';

  @override
  String get cardRecord => 'Record';

  @override
  String get cardSignatureMove => 'Signature move';

  @override
  String get cardSignatureLocked => 'Unlocked from Epic';

  @override
  String get cardHighlights => 'Highlights';

  @override
  String cardStatBonus(int n) {
    return 'Rarity bonus +$n';
  }

  @override
  String cardSerial(int serial, int run) {
    return '$serial/$run';
  }

  @override
  String cardPrintRun(int run) {
    return 'Print run /$run';
  }

  @override
  String get cardRookie => 'Rookie';

  @override
  String cardNumberInSeries(String number, int total) {
    return '$number/$total';
  }

  @override
  String get showcaseIntro =>
      'Every rarity has its own effect. Tap a card to open it, then tilt your phone.';

  @override
  String get showcasePreview => 'Preview';

  @override
  String get profileTitle => 'Profile';

  @override
  String get profileLoading => 'Loading profile…';

  @override
  String get profileOffline => 'Profile unavailable offline';

  @override
  String get administrator => 'Administrator';

  @override
  String get myFriendCode => 'My friend code';

  @override
  String get copy => 'Copy';

  @override
  String get friendCodeCopied => 'Friend code copied';

  @override
  String get settings => 'Settings';

  @override
  String get creditsAndSources => 'Credits and sources';

  @override
  String get settingsTitle => 'Settings';

  @override
  String get account => 'Account';

  @override
  String get syncContent => 'Sync content';

  @override
  String get syncContentSub => 'Fighters, editions, images';

  @override
  String get syncFailed => 'Last attempt failed (offline?)';

  @override
  String get signOut => 'Sign out';

  @override
  String versionLabel(String version) {
    return 'Octogone · version $version';
  }

  @override
  String get creditsTitle => 'Credits';

  @override
  String get creditsDisclaimer =>
      'Personal, non-commercial and unofficial app. No official logos: edition names appear as text and card frames are original designs.';

  @override
  String get dataSources => 'Data sources';

  @override
  String get srcStats => 'Official fighter statistics';

  @override
  String get srcRecords => 'Detailed records, achievements';

  @override
  String get srcNationality => 'Nationality, date of birth';

  @override
  String get srcChecklists => 'Real edition checklists';

  @override
  String get srcChecklistCheck => 'Checklist cross-check';

  @override
  String get srcPhotos => 'Photos';

  @override
  String get srcPhotosWho => 'Wikimedia Commons (free licenses)';

  @override
  String get srcFont => 'Oswald and Barlow fonts (SIL Open Font License)';

  @override
  String get srcSounds => 'Sound effects';

  @override
  String get srcSoundsWho => 'Synthesized for Octogone (no external sounds)';

  @override
  String photosCount(int count) {
    return 'Photos ($count)';
  }

  @override
  String get noPhotos => 'No photos synced.';

  @override
  String photoAuthor(String name) {
    return 'Author: $name';
  }

  @override
  String photoLicense(String name) {
    return 'License: $name';
  }

  @override
  String get fightComing => 'Tactical fights arrive in phase 4.';

  @override
  String get rarityCommune => 'Common';

  @override
  String get rarityPeuCommune => 'Uncommon';

  @override
  String get rarityRare => 'Rare';

  @override
  String get rarityEpique => 'Epic';

  @override
  String get rarityLegendaire => 'Legendary';

  @override
  String get rarityMythique => 'Mythic';

  @override
  String get effectAcier => 'Octagon Steel';

  @override
  String get effectNeon => 'Main Event Neon';

  @override
  String get effectFaceAFace => 'Face-Off';

  @override
  String get effectCicatrice => 'Scar';

  @override
  String get effectOndeDeChoc => 'Shockwave';

  @override
  String get effectCleFatale => 'Fatal Lock';

  @override
  String get effectCeintureOr => 'Gold Belt';

  @override
  String get effectHeritage => 'Legacy';

  @override
  String get effectMoment => 'Historic Moment';

  @override
  String get effectTrilogie => 'Trilogy';

  @override
  String get effectOctogoneNoir => 'Black Octagon';

  @override
  String get effectMainLevee => 'Raised Hand';

  @override
  String get wcPailleF => 'Women\'s Strawweight';

  @override
  String get wcMoucheF => 'Women\'s Flyweight';

  @override
  String get wcCoqF => 'Women\'s Bantamweight';

  @override
  String get wcPlumeF => 'Women\'s Featherweight';

  @override
  String get wcMouche => 'Flyweight';

  @override
  String get wcCoq => 'Bantamweight';

  @override
  String get wcPlume => 'Featherweight';

  @override
  String get wcLegers => 'Lightweight';

  @override
  String get wcMiMoyens => 'Welterweight';

  @override
  String get wcMoyens => 'Middleweight';

  @override
  String get wcMiLourds => 'Light Heavyweight';

  @override
  String get wcLourds => 'Heavyweight';

  @override
  String get statFrappe => 'Striking';

  @override
  String get statPuissance => 'Power';

  @override
  String get statLutte => 'Wrestling';

  @override
  String get statSoumission => 'Submission';

  @override
  String get statDefense => 'Defense';

  @override
  String get statCardio => 'Cardio';

  @override
  String get statMenton => 'Chin';

  @override
  String get statFrappeShort => 'STR';

  @override
  String get statPuissanceShort => 'POW';

  @override
  String get statLutteShort => 'WRE';

  @override
  String get statSoumissionShort => 'SUB';

  @override
  String get statDefenseShort => 'DEF';

  @override
  String get statCardioShort => 'CAR';

  @override
  String get statMentonShort => 'CHN';

  @override
  String get styleFrappeur => 'Striker';

  @override
  String get styleLutteur => 'Wrestler';

  @override
  String get styleGrappler => 'Grappler';

  @override
  String get styleComplet => 'All-rounder';

  @override
  String get boosterOpen => 'Open';

  @override
  String get boosterChooseCollections => 'Choose other collections';

  @override
  String get boosterCollectionsTitle => 'Collections';

  @override
  String boosterCards(int n) {
    return '$n cards';
  }

  @override
  String get boosterStandard => 'Standard';

  @override
  String get boosterPremium => 'Premium';

  @override
  String get boosterEvent => 'Event';

  @override
  String get boosterTestMode => 'Test mode: unlimited boosters';

  @override
  String boosterFreeReady(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count free boosters ready',
      one: '1 free booster ready',
    );
    return '$_temp0';
  }

  @override
  String boosterNextFree(String time) {
    return 'Next free booster in $time';
  }

  @override
  String get boosterNoFree => 'No free booster right now';

  @override
  String boosterPayWithCoins(int price) {
    return 'Open this booster for $price coins?';
  }

  @override
  String boosterPrice(int price) {
    return '$price coins';
  }

  @override
  String get boosterNotEnoughCoins => 'Not enough coins.';

  @override
  String get boosterUnavailable => 'This booster is no longer available.';

  @override
  String get boosterOdds => 'Odds';

  @override
  String boosterOddsPerPack(String n) {
    return '$n per booster';
  }

  @override
  String boosterOddsOneIn(int n) {
    return '1 in $n boosters';
  }

  @override
  String boosterOddsPercent(int pct) {
    return '$pct% of boosters';
  }

  @override
  String boosterPity(int n) {
    return 'At least one Legendary every $n boosters.';
  }

  @override
  String boosterPityLeft(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Guaranteed within $count boosters.',
      one: 'Guaranteed in your next booster at the latest.',
    );
    return '$_temp0';
  }

  @override
  String get boosterNumberedNote =>
      'Numbered cards (/50, 1/1…) exist in limited quantities across all players.';

  @override
  String get boosterTearHint => 'Swipe along the top to tear it open';

  @override
  String get boosterTapToReveal => 'Tap or swipe to reveal';

  @override
  String get boosterTapForNext => 'Swipe or tap for the next one';

  @override
  String get boosterRevealAll => 'Reveal all';

  @override
  String get boosterNew => 'NEW';

  @override
  String get boosterOpenAnother => 'Open another';

  @override
  String get boosterDone => 'Done';

  @override
  String get boosterOpening => 'Opening…';

  @override
  String coins(int n) {
    return '$n coins';
  }

  @override
  String get confirm => 'Confirm';

  @override
  String get cancel => 'Cancel';

  @override
  String get settingsSound => 'Sounds';

  @override
  String get settingsSoundSub => 'Booster tearing and card reveals';

  @override
  String durationHm(int h, int m) {
    return '$h h $m min';
  }

  @override
  String durationM(int m) {
    return '$m min';
  }

  @override
  String get entryCta => 'ENTER THE OCTAGON';

  @override
  String get homeFeatured => 'Featured collection';

  @override
  String get srcPackPhotos => 'Booster pack photos';

  @override
  String get srcPackPhotosWho => 'Official fighter photos (private use)';

  @override
  String get vitrineTitle => 'My showcase';

  @override
  String get vitrineSubtitle => 'Show off your best cards.';

  @override
  String get vitrineEmpty =>
      'Your showcase is empty. Tap a slot to display a card.';

  @override
  String get vitrineReorderHint => 'Long-press and drag to move a card.';

  @override
  String get vitrineHonor => 'Place of honour';

  @override
  String get vitrineEdit => 'Edit';

  @override
  String get vitrineDone => 'Done';

  @override
  String get vitrinePickTitle => 'Pick a card';

  @override
  String get vitrinePickSearch => 'Search a fighter';

  @override
  String get vitrinePickEmpty => 'No card to display.';

  @override
  String get vitrineAdd => 'Add to my showcase';

  @override
  String get vitrineRemove => 'Remove from my showcase';

  @override
  String get vitrineAdded => 'Card added to your showcase.';

  @override
  String get vitrineRemoved => 'Card removed from your showcase.';

  @override
  String get vitrineFull => 'Showcase full: remove a card first.';

  @override
  String vitrineCount(int count, int total) {
    return '$count/$total';
  }

  @override
  String vitrineSaveError(String message) {
    return 'Could not save the showcase: $message';
  }
}
