/// Noms de pays en français (codes ISO 3166-1 alpha-2).
const countryNamesFr = <String, String>{
  'AF': 'Afghanistan', 'AL': 'Albanie', 'DZ': 'Algérie', 'AR': 'Argentine', 'AM': 'Arménie',
  'AU': 'Australie', 'AT': 'Autriche', 'AZ': 'Azerbaïdjan', 'BH': 'Bahreïn', 'BY': 'Biélorussie',
  'BE': 'Belgique', 'BO': 'Bolivie', 'BA': 'Bosnie-Herzégovine', 'BR': 'Brésil', 'BG': 'Bulgarie',
  'CM': 'Cameroun', 'CA': 'Canada', 'CL': 'Chili', 'CN': 'Chine', 'CO': 'Colombie',
  'CD': 'RD Congo', 'CG': 'Congo', 'KR': 'Corée du Sud', 'CR': 'Costa Rica', 'HR': 'Croatie',
  'CU': 'Cuba', 'CY': 'Chypre', 'CZ': 'Tchéquie', 'DK': 'Danemark', 'DO': 'République dominicaine',
  'EC': 'Équateur', 'EG': 'Égypte', 'GB': 'Royaume-Uni', 'EE': 'Estonie', 'FI': 'Finlande',
  'FR': 'France', 'GE': 'Géorgie', 'DE': 'Allemagne', 'GH': 'Ghana', 'GR': 'Grèce',
  'GT': 'Guatemala', 'HT': 'Haïti', 'HN': 'Honduras', 'HU': 'Hongrie', 'IS': 'Islande',
  'IN': 'Inde', 'ID': 'Indonésie', 'IR': 'Iran', 'IQ': 'Irak', 'IE': 'Irlande', 'IL': 'Israël',
  'IT': 'Italie', 'JM': 'Jamaïque', 'JP': 'Japon', 'JO': 'Jordanie', 'KZ': 'Kazakhstan',
  'KE': 'Kenya', 'XK': 'Kosovo', 'KG': 'Kirghizistan', 'LV': 'Lettonie', 'LB': 'Liban',
  'LT': 'Lituanie', 'LU': 'Luxembourg', 'MK': 'Macédoine du Nord', 'MY': 'Malaisie', 'MT': 'Malte',
  'MX': 'Mexique', 'MD': 'Moldavie', 'MN': 'Mongolie', 'ME': 'Monténégro', 'MA': 'Maroc',
  'NL': 'Pays-Bas', 'NZ': 'Nouvelle-Zélande', 'NI': 'Nicaragua', 'NG': 'Nigeria', 'NO': 'Norvège',
  'PK': 'Pakistan', 'PA': 'Panama', 'PY': 'Paraguay', 'PE': 'Pérou', 'PH': 'Philippines',
  'PL': 'Pologne', 'PT': 'Portugal', 'PR': 'Porto Rico', 'RO': 'Roumanie', 'RU': 'Russie',
  'WS': 'Samoa', 'SA': 'Arabie saoudite', 'SN': 'Sénégal', 'RS': 'Serbie', 'SG': 'Singapour',
  'SK': 'Slovaquie', 'SI': 'Slovénie', 'ZA': 'Afrique du Sud', 'ES': 'Espagne', 'SE': 'Suède',
  'CH': 'Suisse', 'SY': 'Syrie', 'TW': 'Taïwan', 'TJ': 'Tadjikistan', 'TH': 'Thaïlande',
  'TN': 'Tunisie', 'TR': 'Turquie', 'TM': 'Turkménistan', 'UG': 'Ouganda', 'UA': 'Ukraine',
  'AE': 'Émirats arabes unis', 'US': 'États-Unis', 'UY': 'Uruguay', 'UZ': 'Ouzbékistan',
  'VE': 'Venezuela', 'VN': 'Viêt Nam', 'ZW': 'Zimbabwe', 'TO': 'Tonga', 'FJ': 'Fidji', 'SR': 'Suriname',
  'CV': 'Cap-Vert', 'AO': 'Angola', 'CI': "Côte d'Ivoire", 'ET': 'Éthiopie', 'TT': 'Trinité-et-Tobago', 'MM': 'Birmanie', 'GY': 'Guyana', 'SU': 'URSS',
};

/// Country names in English (ISO 3166-1 alpha-2).
const countryNamesEn = <String, String>{
  'GY': 'Guyana',
  'SU': 'Soviet Union',
  'AE': 'United Arab Emirates',
  'AF': 'Afghanistan',
  'AL': 'Albania',
  'AM': 'Armenia',
  'AO': 'Angola',
  'AR': 'Argentina',
  'AT': 'Austria',
  'AU': 'Australia',
  'AZ': 'Azerbaijan',
  'BA': 'Bosnia and Herzegovina',
  'BE': 'Belgium',
  'BG': 'Bulgaria',
  'BH': 'Bahrain',
  'BO': 'Bolivia',
  'BR': 'Brazil',
  'BY': 'Belarus',
  'CA': 'Canada',
  'CD': 'DR Congo',
  'CG': 'Congo',
  'CH': 'Switzerland',
  'CI': "Côte d'Ivoire", 'CL': 'Chile',
  'CM': 'Cameroon',
  'CN': 'China',
  'CO': 'Colombia',
  'CR': 'Costa Rica',
  'CU': 'Cuba',
  'CV': 'Cape Verde',
  'CY': 'Cyprus',
  'CZ': 'Czechia',
  'DE': 'Germany',
  'DK': 'Denmark',
  'DO': 'Dominican Republic',
  'DZ': 'Algeria',
  'EC': 'Ecuador',
  'EE': 'Estonia',
  'EG': 'Egypt',
  'ES': 'Spain',
  'ET': 'Ethiopia',
  'FI': 'Finland',
  'FJ': 'Fiji',
  'FR': 'France',
  'GB': 'United Kingdom',
  'GE': 'Georgia',
  'GH': 'Ghana',
  'GR': 'Greece',
  'GT': 'Guatemala',
  'HN': 'Honduras',
  'HR': 'Croatia',
  'HT': 'Haiti',
  'HU': 'Hungary',
  'ID': 'Indonesia',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IN': 'India',
  'IQ': 'Iraq',
  'IR': 'Iran',
  'IS': 'Iceland',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JO': 'Jordan',
  'JP': 'Japan',
  'KE': 'Kenya',
  'KG': 'Kyrgyzstan',
  'KR': 'South Korea',
  'KZ': 'Kazakhstan',
  'LB': 'Lebanon',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'LV': 'Latvia',
  'MA': 'Morocco',
  'MD': 'Moldova',
  'ME': 'Montenegro',
  'MK': 'North Macedonia',
  'MM': 'Myanmar',
  'MN': 'Mongolia',
  'MT': 'Malta',
  'MX': 'Mexico',
  'MY': 'Malaysia',
  'NG': 'Nigeria',
  'NI': 'Nicaragua',
  'NL': 'Netherlands',
  'NO': 'Norway',
  'NZ': 'New Zealand',
  'PA': 'Panama',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PK': 'Pakistan',
  'PL': 'Poland',
  'PR': 'Puerto Rico',
  'PT': 'Portugal',
  'PY': 'Paraguay',
  'RO': 'Romania',
  'RS': 'Serbia',
  'RU': 'Russia',
  'SA': 'Saudi Arabia',
  'SE': 'Sweden',
  'SG': 'Singapore',
  'SI': 'Slovenia',
  'SK': 'Slovakia',
  'SN': 'Senegal',
  'SR': 'Suriname',
  'SY': 'Syria',
  'TH': 'Thailand',
  'TJ': 'Tajikistan',
  'TM': 'Turkmenistan',
  'TN': 'Tunisia',
  'TO': 'Tonga',
  'TR': 'Turkey',
  'TT': 'Trinidad and Tobago',
  'TW': 'Taiwan',
  'UA': 'Ukraine',
  'UG': 'Uganda',
  'US': 'United States',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VE': 'Venezuela',
  'VN': 'Vietnam',
  'WS': 'Samoa',
  'XK': 'Kosovo',
  'ZA': 'South Africa',
  'ZW': 'Zimbabwe',
};
